- name: 'Adding the nginx config'
  become: yes
  template:
    src: '../templates/{{app_name}}/nginx.conf.j2'
    dest: '/etc/nginx/sites-available/{{app_name}}.conf'

- name: 'Symlinking if enabled'
  become: yes
  file:
    src: '/etc/nginx/sites-available/{{app_name}}.conf'
    path: '/etc/nginx/sites-enabled/{{app_name}}.conf'
    state: "{{'link' if enabled is defined and enabled == True else 'absent'}}"
    force: yes # Wtf, for some reason its not yet there ?

- name: 'Restarting nginx'
  become: yes
  service:
    name: 'nginx'
    state: 'restarted'